### PR TITLE
Add minimal MongoDB status logging

### PR DESCRIPTION
**Pull request by shilman**
Give new users a little more info:

```
MBP:server shilman$ yarn start
yarn start v0.21.3
$ babel-node index.js 
Creating development MongoDB on mongodb://localhost:3002
All systems go
API Server is now running on http://localhost:3000
Websocket Server is now running on http://localhost:3001
```

### CODE REVIEW

**Comment by tmeasday** [comment]
LGTM, modolo output app changes.

**Comment by tmeasday** [comment]
@shilman did you want to update the output app here too?

**Comment by shilman** [comment]
Done 👍

**Comment by tmeasday** [comment]
PS Adding you as a maintainer ;)

**Pull request merged**
