### PR TITLE
Fix standard.js error

### PR DESCRIPTION
**Pull request by shilman**
Running standard.js in the resulting project generates the following error, and this fixes it.

```
MBP:server shilman$ standard --fix
standard: Use JavaScript Standard Style (http://standardjs.com)
/Users/shilman/projects/checkin/server/server/index.js:73:3: Do not
use 'new' for side effects.
```

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks for this @shilman.

When updating skel files, we also need to update the `test/output-app` to ensure that the [generation tests](https://github.com/tmeasday/create-graphql-server#testing-full-app-code-generation) still pass. I need to [setup CI](https://github.com/tmeasday/create-graphql-server/issues/19) for this.

**Comment by tmeasday** [comment]
Hey let's get these committed

**Comment by shilman** [comment]
@tmeasday sorry missed your response. Updating.

**Comment by shilman** [comment]
@tmeasday updated

**Pull request merged**
